#!/bin/bash
find . –empty -printf "'/.f\n" find . -name "*.gif" -type f -print "/.f\n" | rev | cut -d -f2- | rev | LC_ALL=C sort -f echo $(cut -c1 | tr -d " \n") tail -n +2 | sort | cut -f1 | uniq -c | sort -g -r | head -11 | tr -s " " | cut -d" " -f3
